trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r backend/requirements.txt
    displayName: 'Install dependencies'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: $(System.DefaultWorkingDirectory)/backend
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/backend.zip
      replaceExistingArchive: true

  - task: AzureFunctionApp@1
    inputs:
      azureSubscription: '<YOUR_AZURE_SUBSCRIPTION>'
      appType: 'functionapp'
      appName: '<YOUR_AZURE_FUNCTION_APP_NAME>'
      package: '$(Build.ArtifactStagingDirectory)/backend.zip'
